version: '3.1'

services:

  wordpress:
    image: custom-wordpress:5.6-php7.2-apache
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - perfecty-net
    volumes:
      - .:/var/www/html/wp-content/plugins/perfecty-push-wp/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: perfecty
      WORDPRESS_DB_NAME: perfecty
      WORDPRESS_DEBUG: 1

  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - perfecty-net
    restart: always
    environment:
      MYSQL_DATABASE: perfecty
      MYSQL_ROOT_PASSWORD: perfecty

networks:
  perfecty-net: